service: sessiondata
runtime: python312  
entrypoint: gunicorn -b :$PORT session_data.wsgi  

# handlers:
#   - url: /static
#     static_dir: static/

#   - url: /.*
#     script: auto

env_variables:
  DJANGO_SETTINGS_MODULE: "session_data.settings"
  SECRET_KEY: ""
  ALLOWED_HOSTS: "*"

# automatic_scaling:
#   target_cpu_utilization: 0.65
#   min_instances: 1
#   max_instances: 5
